FROM ruby:3.4.1-slim

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    git \
    libpq-dev \
    libyaml-dev \
    pkg-config \
    curl \
    postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

WORKDIR /rails

# Install bundler
RUN gem install bundler

ENV RAILS_ENV=development

EXPOSE 3000

CMD ["bin/rails", "server", "-b", "0.0.0.0"]
